services:
  client:
    build: 
      context: ./client
      dockerfile: ./Dockerfile
    container_name: client
    restart: always
    ports:
      - "8088:8088"

  # nginx:
  #   build: ./nginx
  #   container_name: nginx_proxy
  #   environment: 
  #     - ADRTPA_CLIENT=client:3001
  #   # command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
  #   command: /bin/bash -c "nginx -g 'daemon off;"
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - client


  # nginx:
  #   build: ./nginx
  #   container_name: nginx_proxy
  #   environment: 
  #     - ADRTPA_CLIENT=client:3001
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - client